const teams = [
  {
    name: 'Argentina',
    capital: 'Buenos Aires',
    region: 'Americas',
    population: 45376763,
    flag: 'https://flagcdn.com/ar.svg',
    players: [],
  },
  {
    name: 'Australia',
    capital: 'Canberra',
    region: 'Oceania',
    population: 25687041,
    flag: 'https://flagcdn.com/au.svg',
    players: [],
  },
  {
    name: 'Brazil',
    capital: 'Brasília',
    region: 'Americas',
    population: 212559409,
    flag: 'https://flagcdn.com/br.svg',
    players: [],
  },
  {
    name: 'Canada',
    capital: 'Ottawa',
    region: 'Americas',
    population: 38005238,
    flag: 'https://flagcdn.com/ca.svg',
    players: [],
  },
  {
    name: 'China',
    capital: 'Beijing',
    region: 'Asia',
    population: 1402112000,
    flag: 'https://flagcdn.com/cn.svg',
    players: [],
  },
  {
    name: 'Colombia',
    capital: 'Bogotá',
    region: 'Americas',
    population: 50882884,
    flag: 'https://flagcdn.com/co.svg',
    players: [],
  },
  {
    name: 'Costa Rica',
    capital: 'San José',
    region: 'Americas',
    population: 5094114,
    flag: 'https://flagcdn.com/cr.svg',
    players: [],
  },
  {
    name: 'Denmark',
    capital: 'Copenhagen',
    region: 'Europe',
    population: 5831404,
    flag: 'https://flagcdn.com/dk.svg',
    players: [],
  },
  {
    name: 'England',
    capital: 'London',
    region: 'Europe',
    population: 67215293,
    flag: 'https://flagcdn.com/gb.svg',
    players: [],
  },
  {
    name: 'France',
    capital: 'Paris',
    region: 'Europe',
    population: 67391582,
    flag: 'https://flagcdn.com/fr.svg',
    players: [],
  },
  {
    name: 'Germany',
    capital: 'Berlin',
    region: 'Europe',
    population: 83240525,
    flag: 'https://flagcdn.com/de.svg',
    players: [],
  },
  {
    name: 'Haiti',
    capital: 'Port-au-Prince',
    region: 'Americas',
    population: 11402533,
    flag: 'https://flagcdn.com/ht.svg',
    players: [],
  },
  {
    name: 'Italy',
    capital: 'Rome',
    region: 'Europe',
    population: 59554023,
    flag: 'https://flagcdn.com/it.svg',
    players: [],
  },
  {
    name: 'Jamaica',
    capital: 'Kingston',
    region: 'Americas',
    population: 2961161,
    flag: 'https://flagcdn.com/jm.svg',
    players: [],
  },
  {
    name: 'Japan',
    capital: 'Tokyo',
    region: 'Asia',
    population: 125836021,
    flag: 'https://flagcdn.com/jp.svg',
    players: [],
  },
  {
    name: 'Korea Republic',
    capital: 'Seoul',
    region: 'Asia',
    population: 51780579,
    flag: 'https://flagcdn.com/kr.svg',
    players: [],
  },
  {
    name: 'Morocco',
    capital: 'Rabat',
    region: 'Africa',
    population: 36910558,
    flag: 'https://flagcdn.com/ma.svg',
    players: [],
  },
  {
    name: 'Netherlands',
    capital: 'Amsterdam',
    region: 'Europe',
    population: 17441139,
    flag: 'https://flagcdn.com/nl.svg',
    players: [],
  },
  {
    name: 'New Zealand',
    capital: 'Wellington',
    region: 'Oceania',
    population: 5084300,
    flag: 'https://flagcdn.com/nz.svg',
    players: [],
  },
  {
    name: 'Nigeria',
    capital: 'Abuja',
    region: 'Africa',
    population: 206139587,
    flag: 'https://flagcdn.com/ng.svg',
    players: [],
  },
  {
    name: 'Norway',
    capital: 'Oslo',
    region: 'Europe',
    population: 5379475,
    flag: 'https://flagcdn.com/no.svg',
    players: [],
  },
  {
    name: 'Panama',
    capital: 'Panama City',
    region: 'Americas',
    population: 4314768,
    flag: 'https://flagcdn.com/pa.svg',
    players: [],
  },
  {
    name: 'Philippines',
    capital: 'Manila',
    region: 'Asia',
    population: 109581085,
    flag: 'https://flagcdn.com/ph.svg',
    players: [],
  },
  {
    name: 'Portugal',
    capital: 'Lisbon',
    region: 'Europe',
    population: 10305564,
    flag: 'https://flagcdn.com/pt.svg',
    players: [],
  },
  {
    name: 'Ireland',
    capital: 'Dublin',
    region: 'Europe',
    population: 4994724,
    flag: 'https://flagcdn.com/ie.svg',
    players: [],
  },
  {
    name: 'South Africa',
    capital: 'Pretoria',
    region: 'Africa',
    population: 59308690,
    flag: 'https://flagcdn.com/za.svg',
    players: [],
  },
  {
    name: 'Spain',
    capital: 'Madrid',
    region: 'Europe',
    population: 47351567,
    flag: 'https://flagcdn.com/es.svg',
    players: [],
  },
  {
    name: 'Sweden',
    capital: 'Stockholm',
    region: 'Europe',
    population: 10353442,
    flag: 'https://flagcdn.com/se.svg',
    players: [],
  },
  {
    name: 'Switzerland',
    capital: 'Bern',
    region: 'Europe',
    population: 8636896,
    flag: 'https://flagcdn.com/ch.svg',
    players: [],
  },
  {
    name: 'United States',
    capital: 'Washington, D.C.',
    region: 'Americas',
    population: 329484123,
    flag: 'https://flagcdn.com/us.svg',
    players: [],
  },
  {
    name: 'Vietnam',
    capital: 'Hanoi',
    region: 'Asia',
    population: 97338583,
    flag: 'https://flagcdn.com/vn.svg',
    players: [],
  },
  {
    name: 'Zambia',
    capital: 'Lusaka',
    region: 'Africa',
    population: 18383956,
    flag: 'https://flagcdn.com/zm.svg',
    players: [],
  },
];

export { teams };
