const teams = [
  {
    name: 'Argentina',
    capital: 'Buenos Aires',
    code: 'ARG',
    region: 'Americas',
    population: 45376763,
    flag: 'https://flagcdn.com/ar.svg',
    players: {
      goalkeeper: [
        {
          name: 'Vanina Correa',
          img: 'https://digitalhub.fifa.com/transform/cd057c0d-cc00-4132-937f-6b69df5dedad/?io=transform:fill,width:264,height:300',
        },
        {
          name: 'Lara Esponda',
          img: 'https://digitalhub.fifa.com/transform/19fb48a4-8333-4764-8e68-2ee76deb065f/?io=transform:fill,width:264,height:300',
        },
        {
          name: 'Abigail Chaves',
          img: 'https://digitalhub.fifa.com/transform/9c7fa3ac-b7aa-476b-bf94-adc5878c9c17/?io=transform:fill,width:264,height:300',
        },
      ],
      defender: [
        {
          name: 'Adriana Sachs',
          img: 'https://digitalhub.fifa.com/transform/5992d863-6a81-407b-99fd-4d15ad0ebb25/?io=transform:fill,width:264,height:300',
        },
        {
          name: 'Eliana Stábile',
          img: 'https://digitalhub.fifa.com/transform/f5ea9e38-bbb4-481a-b7bd-25af0cfbba42/?io=transform:fill,width:264,height:300',
        },
        {
          name: 'Julieta Cruz',
          img: 'https://digitalhub.fifa.com/transform/f4dcaa27-089a-480a-a535-dbdc0ddf0395/?io=transform:fill,width:264,height:300',
        },
        {
          name: 'Alda Cometti',
          img: 'https://digitalhub.fifa.com/transform/7f4a693b-87e0-4c5c-a78c-f20b65f3efff/?io=transform:fill,width:264,height:300',
        },
        {
          name: 'Sophia Braun',
          img: 'https://digitalhub.fifa.com/transform/9cdb8694-af74-4bc4-9f64-2e834fdf7e8c/?io=transform:fill,width:264,height:300',
        },
        {
          name: 'Miriam Mayorga',
          img: 'https://digitalhub.fifa.com/transform/3c8b10f8-a645-4466-a587-737667de48d0/?io=transform:fill,width:264,height:300',
        },
        {
          name: 'Gabriela Chávez',
          img: 'https://digitalhub.fifa.com/transform/a2c9cdab-c911-441a-99ec-e5ca50f5d341/?io=transform:fill,width:264,height:300',
        },
      ],
      midfield: [
        {
          name: 'Vanessa Santana',
          img: 'https://digitalhub.fifa.com/transform/af9ff8ce-6046-4d8a-bb39-145900b61125/?io=transform:fill,width:264,height:300',
        },
        {
          name: 'Romina Núñez',
          img: 'https://digitalhub.fifa.com/transform/1b78dd4c-4675-41be-9a85-c500acd48d63/?io=transform:fill,width:264,height:300',
        },
        {
          name: 'Daiana Faltán',
          img: 'https://digitalhub.fifa.com/transform/2b674faa-44e5-4e2e-acf8-f2c95e4d117c/?io=transform:fill,width:264,height:300',
        },
        {
          name: 'Dalila Ippolito',
          img: 'https://digitalhub.fifa.com/transform/d3b46f41-1cbc-40a1-895a-6aab1c0d897e/?io=transform:fill,width:264,height:300',
        },
        {
          name: 'Florencia',
          img: 'https://digitalhub.fifa.com/transform/a7887241-c1fe-4956-8e3c-1ce7a1af0144/?io=transform:fill,width:264,height:300',
        },
        {
          name: 'Lorena Benítez',
          img: 'https://digitalhub.fifa.com/transform/290870a5-5051-404c-a524-6be80d2965f0/?io=transform:fill,width:264,height:300',
        },
        {
          name: 'Camila Gómez Ares',
          img: 'https://digitalhub.fifa.com/transform/85180595-ee8a-4c85-bc93-4c174b42cce8/?io=transform:fill,width:264,height:300',
        },
      ],
      attacker: [
        {
          name: 'Estefanía Banini',
          img: 'https://digitalhub.fifa.com/transform/272c66b5-5d9c-468f-a3a8-6bda455e68d3/?io=transform:fill,width:264,height:300',
        },
        {
          name: 'Paulina Gramaglia',
          img: 'https://digitalhub.fifa.com/transform/06f656a5-9c29-44f7-85a3-13a54128c5af/?io=transform:fill,width:264,height:300',
        },
        {
          name: 'Yamila Rodríguez',
          img: 'https://digitalhub.fifa.com/transform/1274a494-2e72-456f-8473-193c6904cc79/?io=transform:fill,width:264,height:300',
        },
        {
          name: 'Mariana Larroquette',
          img: 'https://digitalhub.fifa.com/transform/8a5656fe-58f9-42e7-804c-a9c071f4c12a/?io=transform:fill,width:264,height:300',
        },
        {
          name: 'Chiara Singarella',
          img: 'https://digitalhub.fifa.com/transform/53d06ecb-b1bd-4974-8878-39fe7032f5f0/?io=transform:fill,width:264,height:300',
        },
        {
          name: 'Érica Lonigro',
          img: 'https://digitalhub.fifa.com/transform/560f0948-5d09-4846-8edf-a0ede9051999/?io=transform:fill,width:264,height:300',
        },
      ],
      coach: {
        name: 'Germán Portanova',
        img: 'https://digitalhub.fifa.com/transform/aa8f9cdc-eef0-446e-8a6d-33088d0eb508/Argentina-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:264,height:300',
      },
    },
  },
  {
    name: 'Australia',
    capital: 'Canberra',
    code: 'AUS',
    region: 'Oceania',
    population: 25687041,
    flag: 'https://flagcdn.com/au.svg',
    players: {
      goalkeeper: [
        {
          name: 'Lydia WILLIAMS',
          img: 'https://digitalhub.fifa.com/transform/bc19f8c8-597a-42df-ba80-9ad8f10ac456/Australia-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Teagan MICAH',
          img: 'https://digitalhub.fifa.com/transform/9b6cea0f-4295-4943-8a72-3b27e81fc10a/Australia-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Mackenzie ARNOLD',
          img: 'https://digitalhub.fifa.com/transform/b6b29769-961c-4adc-9a98-61a59f1c5a4c/Australia-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
      ],
      defender: [
        {
          name: 'Courtney NEVIN',
          img: 'https://digitalhub.fifa.com/transform/6afaa153-7e02-4d90-b77d-9aab28c7a70d/Australia-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Aivi LUIK',
          img: 'https://digitalhub.fifa.com/transform/66d45f36-5caf-4d79-a0cc-5718bef4ce5d/Australia-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Clare POLKINGHORNE',
          img: 'https://digitalhub.fifa.com/transform/f32a1b18-0c12-4176-8154-f5befaddff34/Australia-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Steph CATLEY',
          img: 'https://digitalhub.fifa.com/transform/eee94407-004c-43a1-93d8-f1cdeb060d1f/Australia-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Alanna KENNEDY',
          img: 'https://digitalhub.fifa.com/transform/432742d5-0668-415d-a612-e6d365e3fe9c/Australia-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Clare HUNT',
          img: 'https://digitalhub.fifa.com/transform/84459cd5-7ca8-4a03-8591-a13ff96b0c2a/Australia-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Ellie CARPENTER',
          img: 'https://digitalhub.fifa.com/transform/48e30b09-c895-44aa-899a-9af3af2081f3/Australia-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Charlotte GRANT',
          img: 'https://www.canva.com/design/DAFpZbzk0GY/',
        },
      ],
      midfield: [
        {
          name: 'Clare WHEELER',
          img: 'https://digitalhub.fifa.com/transform/63795416-596c-4ee2-a356-3268d74b4c13/Australia-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Alex CHIDIAC',
          img: 'https://digitalhub.fifa.com/transform/cbf0979c-2b4b-4ce9-ac5f-3b1f71960ae8/Australia-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Emily VAN EGMOND',
          img: 'https://digitalhub.fifa.com/transform/85a814cb-17cb-477b-bcd4-7d2de4b4d955/Australia-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Tameka YALLOP',
          img: 'https://digitalhub.fifa.com/transform/edf41884-c7c6-477f-be4a-9c2efb4c86a1/Australia-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Katrina GORRY',
          img: 'https://digitalhub.fifa.com/transform/12c6127b-0e2d-4554-81cc-f84f31d9a20c/Australia-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Kyra COONEY-CROSS',
          img: 'https://digitalhub.fifa.com/transform/a0be21b4-0ae4-4937-a23d-5eed4ce5a4fd/Australia-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
      ],
      attacker: [
        {
          name: 'Cortnee VINE',
          img: 'https://digitalhub.fifa.com/transform/53a840eb-fe3c-4385-a701-c6122af058d8/Australia-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Caitlin FOORD',
          img: 'https://digitalhub.fifa.com/transform/a0229a12-406e-442f-85d1-0ed5e07cd12e/Australia-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Mary FOWLER',
          img: 'https://digitalhub.fifa.com/transform/f113fc62-ccfd-42b2-96f5-97129faff97e/Australia-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Hayley RASO',
          img: 'https://digitalhub.fifa.com/transform/3553656d-80eb-4560-813e-d845b2447510/Australia-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Kyah SIMON',
          img: 'https://digitalhub.fifa.com/transform/c6e1ea68-a1c1-45dd-b8bf-833c1883793b/Australia-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Sam KERR',
          img: 'https://digitalhub.fifa.com/transform/7b61165a-5f23-4086-b8d5-6f767a8216bd/Australia-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
      ],
      coach: {
        name: 'Tony Gustavsson',
        img: 'https://digitalhub.fifa.com/transform/147099e2-bdb4-4802-b5c1-82c724051ea4/Australia-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:264,height:300',
      },
    },
  },
  {
    name: 'Brazil',
    capital: 'Brasília',
    code: 'BRA',
    region: 'Americas',
    population: 212559409,
    flag: 'https://flagcdn.com/br.svg',
    players: {
      goalkeeper: [
        {
          name: 'Bárbara',
          img: 'https://digitalhub.fifa.com/transform/d808f022-38db-4a2f-aac0-c533d8cc1326/1556714212?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Letícia Izidoro',
          img: 'https://digitalhub.fifa.com/transform/e23a5538-1aca-4eab-98b9-d1b5e6919f30/1556714218?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Camila',
          img: 'https://digitalhub.fifa.com/transform/2bca0d55-f03f-4bf7-9825-09e5ea280261/1556714720?io=transform:fill,width:792,height:900',
        },
      ],
      defender: [
        {
          name: 'Antonia',
          img: 'https://digitalhub.fifa.com/transform/6915b6a2-c4ae-4969-a559-f13476fb4954/1556715229?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Tamires',
          img: 'https://digitalhub.fifa.com/transform/7db8f79b-622e-435c-9213-b0bcaf726678/1556716781?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Bruninha',
          img: 'https://digitalhub.fifa.com/transform/f76f9c93-8cc7-4b9f-9758-5623c6407501/1556721958?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Kathellen',
          img: 'https://digitalhub.fifa.com/transform/5f0f7663-5bf8-4738-898e-ce8c850d6fff/1556434301?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Rafaelle',
          img: 'https://digitalhub.fifa.com/transform/0bca8912-4df1-4b2a-8bb0-263ff89884c5/1556434840?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Lauren',
          img: 'https://digitalhub.fifa.com/transform/c56fec4e-009d-4b93-b65b-b90be064f58f/1556722469?io=transform:fill,width:792,height:900',
        },
      ],
      midfield: [
        {
          name: 'Luana',
          img: 'https://digitalhub.fifa.com/transform/15456d21-9b8c-48bc-a68e-7d76c20e61da/1556716272?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Mônica Hickman',
          img: 'https://digitalhub.fifa.com/transform/f1ff4d8e-5714-4494-bab2-2cabbc335ec9/1556724717?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Ana Vitória',
          img: 'https://digitalhub.fifa.com/transform/58f6ede2-e6c4-4024-838d-ad002e10c211/1556717312?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Adriana',
          img: 'https://digitalhub.fifa.com/transform/b56c5095-32a7-471f-9dee-825993cd8991/1556721949?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Ary Borges',
          img: 'https://digitalhub.fifa.com/transform/9c906efd-d238-42ee-bb4a-3c2edfecba51/1556723995?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Angelina',
          img: 'https://digitalhub.fifa.com/transform/e0ca5f23-e950-4d60-b067-470a9d205742/1556725041?io=transform:fill,width:792,height:900',
        },
      ],
      attacker: [
        {
          name: 'Andressa Alves',
          img: 'https://digitalhub.fifa.com/transform/73e0c4d0-3f85-4678-8cf0-074fac9c6fc2/1556717299?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Duda Sampaio',
          img: 'https://digitalhub.fifa.com/transform/153bd7a6-3878-47d9-8146-dc2e503029ff/1556722979?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Kerolin',
          img: 'https://digitalhub.fifa.com/transform/586daffe-bf8c-44ff-84a1-321ba38d4213/1556725548?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Debinha',
          img: 'https://digitalhub.fifa.com/transform/2446727f-c33e-4224-8f51-7636d405649c/1556721443?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Marta',
          img: 'https://digitalhub.fifa.com/transform/27b226f4-fe77-46c3-b44a-59151f6f8c68/1556721444?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Bia Zaneratto',
          img: 'https://digitalhub.fifa.com/transform/a02e0fa2-4212-48fc-955c-54a3000802f6/1556722981?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Geyse',
          img: 'https://digitalhub.fifa.com/transform/cf028091-cb27-4ad1-88c9-97e738c9d251/1556724518?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Gabi Nunes',
          img: 'https://digitalhub.fifa.com/transform/917cfeae-99d6-408d-a84a-b5ec4dfaed72/1556725554?io=transform:fill,width:792,height:900',
        },
      ],
      coach: {
        name: 'Pia Sundhage',
        img: 'https://digitalhub.fifa.com/transform/ed1c772f-88e0-438a-9aad-daf27b8af959/1556713702?io=transform:fill,width:264,height:300',
      },
    },
  },
  {
    name: 'Canada',
    capital: 'Ottawa',
    code: 'CAN',
    region: 'Americas',
    population: 38005238,
    flag: 'https://flagcdn.com/ca.svg',
    players: {
      goalkeeper: [
        {
          name: 'Kailen SHERIDAN',
          img: 'https://digitalhub.fifa.com/transform/af578751-bbb9-4e0b-92ef-955a9d64984d/Canada-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Sabrina DANGELO',
          img: 'https://digitalhub.fifa.com/transform/687d60db-fce8-42d4-b07c-20d1157f7fd7/Canada-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Lysianne PROULX',
          img: 'https://digitalhub.fifa.com/transform/eafe0cdb-e83b-4386-9352-c40bdeb5d6a0/Canada-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
      ],
      defender: [
        {
          name: 'Allysha CHAPMAN',
          img: 'https://digitalhub.fifa.com/transform/f2442707-7f6c-4df2-bd4b-8ae6cd474ca1/Canada-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Kadeisha BUCHANAN',
          img: 'https://digitalhub.fifa.com/transform/391711d8-1035-48db-a2af-228f42624ae1/Canada-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Shelina ZADORSKY',
          img: 'https://digitalhub.fifa.com/transform/c30808e7-cc7f-4342-af5d-8bbb7c6b4a3b/Canada-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Jayde RIVIERE',
          img: 'https://digitalhub.fifa.com/transform/704907c9-d5d3-4958-b9cf-83a959053a91/Canada-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Ashley LAWRENCE',
          img: 'https://digitalhub.fifa.com/transform/eab717bb-ffe1-4b50-91b5-4b4582fbd794/Canada-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Vanessa GILLES',
          img: 'https://digitalhub.fifa.com/transform/23b73512-92a3-4132-a159-af9e16a9f888/Canada-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Gabrielle CARLE',
          img: 'https://digitalhub.fifa.com/transform/b8e952ab-4513-4330-b609-04670104a748/Canada-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
      ],
      midfield: [
        {
          name: 'QUINN',
          img: 'https://digitalhub.fifa.com/transform/f67e383b-5565-47df-85b7-427f0b11315a/Canada-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Julia GROSSO',
          img: 'https://digitalhub.fifa.com/transform/1b524686-b128-4c1e-940c-03d5fc9d0f13/Canada-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Sophie SCHMIDT',
          img: 'https://digitalhub.fifa.com/transform/e113f761-4ef2-48a9-b91e-2175887cb9ee/Canada-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Jessie FLEMING',
          img: 'https://digitalhub.fifa.com/transform/736142dd-8ecb-4eb3-845a-b0427a7d8ab4/Canada-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Simi AWUJO',
          img: 'https://digitalhub.fifa.com/transform/950359af-ac57-45b1-b054-3e36611c4538/Canada-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
      ],
      attacker: [
        {
          name: 'Deanne ROSE',
          img: 'https://digitalhub.fifa.com/transform/85be5844-e7d3-45e2-86e4-11173694cbb3/Canada-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Jordyn HUITEMA',
          img: 'https://digitalhub.fifa.com/transform/bc0155ca-514a-48aa-b5b7-b2733854d3ee/Canada-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Evelyne VIENS',
          img: 'https://digitalhub.fifa.com/transform/7c8e43cf-4e57-4ba7-b730-7625db434820/Canada-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Christine SINCLAIR',
          img: 'https://digitalhub.fifa.com/transform/00e96f48-57e1-4ac3-b4bd-66f6a86e9189/Canada-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Nichelle PRINCE',
          img: 'https://digitalhub.fifa.com/transform/57c3254d-a747-4638-830b-0852a3eccc47/Canada-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Adriana LEON',
          img: 'https://digitalhub.fifa.com/transform/b863e80d-4193-4176-ad8e-a7ada025e924/Canada-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Cloe LACASSE',
          img: 'https://digitalhub.fifa.com/transform/47cd379b-170c-4bed-a1f2-48251f1df76e/Canada-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Olivia SMITH',
          img: 'https://digitalhub.fifa.com/transform/12b36bf9-cc04-4acc-8dbc-9c6fbc3b2b4f/Canada-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
      ],
      coach: {
        name: 'Beverly Priestman',
        img: 'https://digitalhub.fifa.com/transform/74ec3eca-afb2-4b23-864a-bc71c3d2566b/Canada-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:264,height:300',
      },
    },
  },
  {
    name: 'China',
    capital: 'Beijing',
    code: 'CHN',
    region: 'Asia',
    population: 1402112000,
    flag: 'https://flagcdn.com/cn.svg',
    players: {
      goalkeeper: [
        {
          name: 'ZHU Yu',
          img: 'https://digitalhub.fifa.com/transform/1e494dda-a4c5-4dae-9cf8-5090d853f770/China-PR-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'XU Huan',
          img: 'https://digitalhub.fifa.com/transform/c1d86a33-cfd5-4eb9-b55e-e4dd81e12425/China-PR-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'PAN Hongyan',
          img: 'https://digitalhub.fifa.com/transform/53467760-d144-476b-82ca-6e76f4db046e/China-PR-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
      ],
      defender: [
        {
          name: 'LI Mengwen',
          img: 'https://digitalhub.fifa.com/transform/511e52f4-9e29-41e0-a850-000e9a1b65b4/China-PR-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'DOU Jiaxing',
          img: 'https://digitalhub.fifa.com/transform/3acd4712-1da3-4aa7-a76a-bf342bb953b7/China-PR-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'WANG Linlin',
          img: 'https://digitalhub.fifa.com/transform/7b6ebe21-2a9e-4ad3-840a-f6deb4f5c95a/China-PR-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'WU Haiyan',
          img: 'https://digitalhub.fifa.com/transform/6c2b8da7-b994-448b-84b3-dd30aefa933c/China-PR-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'YAO Wei',
          img: 'https://digitalhub.fifa.com/transform/371b1732-76a3-4760-814f-00c14ec6fbf5/China-PR-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Miriam',
          img: 'https://digitalhub.fifa.com/transform/15e1a623-cc40-4df6-928a-2d6b32239085/China-PR-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'CHEN Qiaozhu',
          img: 'https://digitalhub.fifa.com/transform/99dcd8f9-8232-4f16-b268-61f6406148d5/China-PR-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
      ],
      midfield: [
        {
          name: 'GAO Chen',
          img: 'https://digitalhub.fifa.com/transform/67bde3da-e81e-46d0-9719-db1be755a55e/China-PR-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'ZHANG Xin',
          img: 'https://digitalhub.fifa.com/transform/0d7dfb20-27d8-4148-a612-96e34a4d27bf/China-PR-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'SHEN Mengyu',
          img: 'https://digitalhub.fifa.com/transform/e2ef324e-0901-4938-8629-a4e230064c9f/China-PR-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'ZHANG Rui',
          img: 'https://digitalhub.fifa.com/transform/bc45ff0b-c5c4-4e45-a2d4-6ee281a85ea6/China-PR-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'Florencia',
          img: 'https://digitalhub.fifa.com/transform/9badff62-aaf2-46ff-9a6e-3afa2a34dbed/China-PR-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'YANG Lina',
          img: 'https://digitalhub.fifa.com/transform/977ca6b1-ea51-40dd-a364-ff757dacd54d/China-PR-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'YAO Lingwei',
          img: 'https://digitalhub.fifa.com/transform/7f3fff84-005b-4fc0-854e-f97efc30e387/CHINA-Headshots?io=transform:fill,width:792,height:900',
        },
        {
          name: 'WU Chengshu',
          img: 'https://digitalhub.fifa.com/transform/063ece3c-ad6f-4d72-8137-2f954e557820/China-PR-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
      ],
      attacker: [
        {
          name: 'ZHANG Linyan',
          img: 'https://digitalhub.fifa.com/transform/d49db1b5-1773-4c67-9bb9-ed9d24dfea50/China-PR-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'GU Yasha',
          img: 'https://digitalhub.fifa.com/transform/c11adc71-6039-4517-9d59-0a4c06b29186/China-PR-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'WANG Shuang',
          img: 'https://digitalhub.fifa.com/transform/1d647fb7-7034-440e-8fd1-4af463b30dee/China-PR-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'WANG Shanshan',
          img: 'https://digitalhub.fifa.com/transform/010f8a6b-4958-434b-86c2-341a0adef103/China-PR-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
        {
          name: 'LOU Jiahui',
          img: 'https://digitalhub.fifa.com/transform/ee6276f3-61c6-40ba-9a8c-9af2a31f1a09/China-PR-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:792,height:900',
        },
      ],
      coach: {
        name: 'Shui Qingxia',
        img: 'https://digitalhub.fifa.com/transform/4c27a044-cbdb-43d8-85de-a99c0cfc2235/China-PR-Portraits-FIFA-Women-s-World-Cup-Australia-New-Zealand-2023?io=transform:fill,width:264,height:300',
      },
    },
  },
  {
    name: 'Colombia',
    capital: 'Bogotá',
    code: 'COL',
    region: 'Americas',
    population: 50882884,
    flag: 'https://flagcdn.com/co.svg',
    players: {
      goalkeeper: ['Catalina Pérez', 'Nathalia Giraldo', 'Sandra Sepúlveda'],
      defender: [
        'Ana María Guzmán',
        'Ángela Barón',
        'Carolina Arias',
        'Daniela Arias',
        'Daniela Caracas',
        'Jorelyn Carabalí',
        'Manuela Vanegas',
      ],
      midfield: [
        'Catalina Usme',
        'Daniela Montoya',
        'Diana Ospina',
        'Lorena Bedoya',
        'Marcela Restrepo',
        'María Camila Reyes',
        'Mónica Ramos',
      ],
      attacker: [
        'Elexa Bahr',
        'Ivonne Chacón',
        'Lady Andrade',
        'Leicy Santos',
        'Linda Caicedo',
        'Mayra Ramírez',
      ],
      coach: 'Nelson Abadía',
    },
  },
  {
    name: 'Costa Rica',
    capital: 'San José',
    code: 'CRC',
    region: 'Americas',
    population: 5094114,
    flag: 'https://flagcdn.com/cr.svg',
    players: {
      goalkeeper: ['Priscilla Tapia', 'Daniela Solera', 'Génesis Pérez'],
      defender: [
        'Mariana Benavides',
        'Maria Paula Elizondo',
        'Valeria del Campo',
        'Yesmi Rodríguez',
        'Fabíola Villalobos',
        'Maria Coto',
        'Gabriela Guillén',
      ],
      midfield: [
        'Katherine Alvarado',
        'Mariela Campos',
        'Gloriana Villalobos',
        'Emilie Valenciano',
        'Melissa Herrera',
        'Cristin Granados',
        'Alexandra Pineli',
        'Sheika Scott',
        'Raquel Rodríguez',
      ],
      attacker: [
        'Catalina Estrada',
        'Princila Chinchilla',
        'Sofia Varela',
        'Maria Paula Salas',
      ],
      coach: 'Amelia Valverde',
    },
  },
  {
    name: 'Denmark',
    capital: 'Copenhagen',
    code: 'DNK',
    region: 'Europe',
    population: 5831404,
    flag: 'https://flagcdn.com/dk.svg',
    players: {
      goalkeeper: [
        'Lene Christensen',
        'Katrhine Larsen',
        'Maja Bay Ostergaard',
      ],
      defender: [
        'Luna Gevitz',
        'Stine Pedersen',
        'Rikke Sevecke',
        'Simone Sorensen',
        'Sofie Svava',
        'Frederikke Thogersen',
        'Katrine Veje',
      ],
      midfield: [
        'Josefine Hasbo',
        'Karen Holmgaard',
        'Sofie Pedersen',
        'Kathrine Kühl',
        'Emma Snerle',
        'Nicoline Sorensen',
        'Janni Thomsen',
        'Sanne Nielsen',
      ],
      attacker: [
        'Signe Bruun',
        'Mille Gejl',
        'Pernille Harder',
        'Rikke Madsen',
        'Amalie Vangsgaard',
      ],
      coach: 'Lars Sondergaard',
    },
  },
  {
    name: 'England',
    capital: 'London',
    code: 'ENG',
    region: 'Europe',
    population: 67215293,
    flag: 'https://flagcdn.com/gb.svg',
    players: {
      goalkeeper: ['Mary Earps', 'Ellie Roebuck', 'Hannah Hampton'],
      defender: [
        'Lucy Bronze',
        'Millie Bright',
        'Alex Greenwood',
        'Jess Carter',
        'Esme Morgan',
        'Lotte Wubben-Moy',
        'Niamh Charles',
      ],
      midfield: [
        'Keira Walsh',
        'Georgia Stanway',
        'Ella Toone',
        'Jordan Nobbs',
        'Laura Coombs',
        'Katie Zelem',
      ],
      attacker: [
        'Alessia Russo',
        'Rachel Daly',
        'Lauren James',
        'Chloe Kelly',
        'Lauren Hemp',
        'Katie Robinson',
        'Beth England',
      ],
      coach: 'Sarina Wiegman',
    },
  },
  {
    name: 'France',
    capital: 'Paris',
    code: 'FRA',
    region: 'Europe',
    population: 67391582,
    flag: 'https://flagcdn.com/fr.svg',
    players: {
      goalkeeper: [
        'Solène Durand',
        'Pauline Peyraud-Magnin',
        'Constance Picaud',
      ],
      defender: [
        'Selma Bacha',
        'Estelle Cascarino',
        'Elisa de Almeida',
        'Sakina Karchaoui',
        'Maëlle Lakrar',
        'Eve Perisset',
        'Wendie Renard',
      ],
      midfield: [
        'Kenza Dali',
        'Laurina Fazer',
        'Grace Geyoro',
        'Léa Le Garrec',
        'Amel Majri',
        'Sandie Toletti',
        'Aïssatou Tounkara',
      ],
      attacker: [
        'Viviane Asseyi',
        'Vicki Becho',
        'Kadidiatou Diani',
        'Eugénie Le Sommer',
        'Clara Mateo',
        'Naomie Feller',
      ],
      coach: 'Hervé Renard',
    },
  },
  {
    name: 'Germany',
    capital: 'Berlin',
    code: 'GER',
    region: 'Europe',
    population: 83240525,
    flag: 'https://flagcdn.com/de.svg',
    players: {
      goalkeeper: ['Ann-Katrin Berger', 'Merle Frohms', 'Stina Johannes'],
      defender: [
        'Sara Doorsoun',
        'Marina Hegering',
        'Kathrin Hendrich',
        'Sophia Kleinhern',
        'Sjoeke Nüsken',
        'Felicitas Rauch',
      ],
      midfield: [
        'Jule Brand',
        'Klara Bühl',
        'Sara Däbritz',
        'Chantal Hagel',
        'Lena Lattwein',
        'Melanie Leupolz',
        'Sydney Lohmann',
        'Lina Magull',
        'Lena Oberdorf',
      ],
      attacker: [
        'Alexandra Popp',
        'Svenja Huth',
        'Laura Freigang',
        'Lea Schüller',
        'Nicole Anyomi',
      ],
      coach: 'Martina Voss-Tecklenburg',
    },
  },
  {
    name: 'Haiti',
    capital: 'Port-au-Prince',
    code: 'HAI',
    region: 'Americas',
    population: 11402533,
    flag: 'https://flagcdn.com/ht.svg',
    players: {
      goalkeeper: ['Nahomie Abroise', 'Lara Larco', 'Kerly Théus'],
      defender: [
        'Esthericove Joseph',
        'Tabita Joseph',
        'Kethna Louis',
        'Ruthny Mathurin',
        'Betina Petit-Frère',
        'Milan Pierre-Jérôme',
        'Chelsea Surpris',
      ],
      midfield: [
        'Michele Dumornay',
        'Danielle Étienne',
        'Noa Ganthier',
        'Sherly Jeudy',
        'Jennyfer Limage',
        'Maudeline Moryl',
        'Dayana Pierre-Louis',
      ],
      attacker: [
        'Roselord Borgella',
        'Roseline Éloissaint',
        'Darlina Joseph',
        'Shwendesky Joseph',
        'Batcheba Louis',
        'Nérilia Mondésir',
      ],
      coach: 'Nicolas Delépine',
    },
  },
  {
    name: 'Italy',
    capital: 'Rome',
    code: 'ITA',
    region: 'Europe',
    population: 59554023,
    flag: 'https://flagcdn.com/it.svg',
    players: {
      goalkeeper: ['Laura Giuliane', 'Francesca Durante', 'Rachele Baldi'],
      defender: [
        'Elena Linari',
        'Elisa Bartoli',
        'Lisa Boattin',
        'Cecilia Salvai',
        'Martina Lenzini',
        'Lucia Di Guglielmo',
        'Benedetta Orsi',
      ],
      midfield: [
        'Valentina Cernoia',
        'Manuela Giugliano',
        'Arianna Caruso',
        'Giada Greggi',
        'Emma Severini',
        'Giulia Dragoni',
      ],
      attacker: [
        'Cristiana Girelli',
        'Barbara Bonansea',
        'Valentina Giacinti',
        'Annamaria Serturini',
        'Benedetta Glionna',
        'Sofia Cantore',
        'Chiara Beccari',
      ],
      coach: 'Milena Bertolini',
    },
  },
  {
    name: 'Jamaica',
    capital: 'Kingston',
    code: 'JAM',
    region: 'Americas',
    population: 2961161,
    flag: 'https://flagcdn.com/jm.svg',
    players: {
      goalkeeper: ['Rebecca Spencer', 'Sydney Schneider', 'Liya Brooks'],
      defender: [
        'Allyson Swaby',
        'Chatelle Swaby',
        'Konya Plummer',
        'Deneisha Blackwood',
        'Vyan Sampson',
        'Tiernny Wiltshire',
      ],
      midfield: [
        'Peyton McNamara',
        'Drew Spence',
        'Trudi Carter',
        'Solai Washington',
        'Atlanta Primus',
        'Havana Solaun',
      ],
      attacker: [
        'hadija "Bunny" Shaw',
        'Jody Brown',
        'Tiffany Cameron',
        'Kameron Simmonds',
        'Kiki van Zanten',
        'Paige Bailey-Gayle',
        'Cheyna Matthews',
        'Kayla McKenna',
      ],
      coach: 'Lorne Donaldson',
    },
  },
  {
    name: 'Japan',
    capital: 'Tokyo',
    code: 'JPN',
    region: 'Asia',
    population: 125836021,
    flag: 'https://flagcdn.com/jp.svg',
    players: {
      goalkeeper: ['Ayaka Yamashita', 'Chika Hirao', 'Momoko Tanaka'],
      defender: [
        'Saki Kumagai',
        'Shiori Miyake',
        'Risa Shimizu',
        'Kiko Seike',
        'Miyabi Moriya',
        'Moeka Minami',
        'Hana Takahashi',
        'Rion Ishikawa',
      ],
      midfield: [
        'Hikaru Naomoto',
        'Yui Hasegawa',
        'Hina Sugita',
        'Honoka Hayashi',
        'Fuka Nagano',
        'Hinata Miyazawa',
        'Jun Endo',
        'Aoba Fujino',
      ],
      attacker: ['Mina Tanaka', 'Remina Chiba', 'Riko Ueki', 'Maika Hamano'],
      coach: '',
    },
  },
  {
    name: 'Korea Republic',
    capital: 'Seoul',
    code: 'KOR',
    region: 'Asia',
    population: 51780579,
    flag: 'https://flagcdn.com/kr.svg',
    players: {
      goalkeeper: ['Kim Jung-mi', 'Yoon Young-geul', 'Ryu Ji-soo'],
      defender: [
        'Kim Hye-ri',
        'Lim Seon-joo',
        'Jang Sei-gi',
        'Shim Seo-yeon',
        'Lee Young-ju',
        'Heong Hye-ji',
        'Choo Hyo-joo',
      ],
      midfield: [
        'Cho So-hyun',
        'Ji So-yun',
        'Lee Geum-min',
        'Jeon Eun-ha',
        'Kim Yun-ji',
        'Chun Ga-ram',
        'Bae Ye-bin',
      ],
      attacker: [
        'Choe Yu-ri',
        'Son Hwa-yeon',
        'Park Eun-sun',
        'Moon Mi-ra',
        'Kang Chae-rim',
        'Casey Phair',
      ],
      coach: 'Colin Bell',
    },
  },
  {
    name: 'Morocco',
    capital: 'Rabat',
    code: 'MAR',
    region: 'Africa',
    population: 36910558,
    flag: 'https://flagcdn.com/ma.svg',
    players: {
      goalkeeper: ['Inès Arouaissa', 'Khadija Er-Rmichi', 'Assia Zouhair'],
      defender: [
        'Hanane Aït El Haj',
        'Nouhaila Benzina',
        'Siham Boukhami',
        'Zineb Redouani',
        'Yasmin Mrabet',
        'Rkia Mazrouai',
        'Nesryne El Chad',
        'Ghizlane Chhiri',
        'Sabah Seghir',
      ],
      midfield: [
        'Najat Badri',
        'Anissa Lahmari',
        'Élodie Nakkach',
        'Sarah Kassi',
        'Fatima Tagnaout',
        'Salma Amani',
      ],
      attacker: [
        'Rosella Ayane',
        'Ghizlane Chebbak',
        'Anissa Belkasmi',
        'Sofia Bouftini',
        'Imane Saoud',
        'Ibtissam Jraidi',
        'Samya Hassani',
        'Kenza Chapelle',
        'Sakina Ouzraoui Diki',
        'Fatima Zohra Gharbi',
      ],
      coach: 'Reynald Pedros',
    },
  },
  {
    name: 'Netherlands',
    capital: 'Amsterdam',
    code: 'NLD',
    region: 'Europe',
    population: 17441139,
    flag: 'https://flagcdn.com/nl.svg',
    players: {
      goalkeeper: [
        'Daphne van Domselaar',
        'Lize Kop',
        'Barbara Lorsheyd',
        'Jacintha Weimar',
      ],
      defender: [
        'Stefanie van der Gragt',
        'Dominique Janssen',
        'Kika van Es',
        'Merel van Dongen',
        'Aniek Nouwen',
        'Lynn Wilms',
        'Caitlin Dijkstra',
        'Alieke Tuin',
      ],
      midfield: [
        'Sherida Spitse',
        'Danielle van de Donk',
        'Jackie Groenen',
        'Jill Roord',
        'Victoria Pelova',
        'Karstin Casparij',
        'Damaris Egurrola',
        'Jil Baijings',
        'Wieke Kaptein',
      ],
      attacker: [
        'Lieke Martens',
        'Shanice van de Sanden',
        'Lineth Beerensteyn',
        'Renate Jansen',
        'Esmee Brugts',
        'Katja Snoeijs',
        'Roméen Leuchter',
        'Fenna Kalma',
        'Tiny Hoekstra',
      ],
      coach: 'Andries Jonker',
    },
  },
  {
    name: 'New Zealand',
    capital: 'Wellington',
    code: 'NZL',
    region: 'Oceania',
    population: 5084300,
    flag: 'https://flagcdn.com/nz.svg',
    players: {
      goalkeeper: ['Victoria Esson', 'Anna Leat', 'Erin Nayler'],
      defender: [
        'Liz Anton',
        'C.J.Bott',
        'Katie Bowen',
        'Claudia Bunge',
        'Michaela Foster',
        'Ali Riley',
        'Rebekah Stott',
      ],
      midfield: [
        'Olivia Chance',
        'Daisy Cleverley',
        'Betsy Hassett',
        'Annalie Longo',
        'Ria Percival',
        'Malia Steinmetz',
      ],
      attacker: [
        'Milly Clegg',
        'Jacqui Hand',
        'Grace Jale',
        'Gabi Rennie',
        'Indiah-Paige Riley',
        'Paige Satchell',
        'Hannah Wilkinson',
      ],
      coach: 'Jitka Klimková',
    },
  },
  {
    name: 'Nigeria',
    capital: 'Abuja',
    code: 'NGA',
    region: 'Africa',
    population: 206139587,
    flag: 'https://flagcdn.com/ng.svg',
    players: {
      goalkeeper: ['Chiamaka Nnadozie', 'Tochukwu Oluehi', 'Yewande Balogun'],
      defender: [
        'Onome Ebi',
        'Osinachi Ohale',
        'Glory Ogbonna',
        'Ashleigh Pluptre',
        'Rofiat Imuran',
        'Michelle Alozie',
        'Oluwatosin Demehin',
      ],
      midfield: [
        'Halimatu Ayinde',
        'Rasheedat Ajibade',
        'Toni Payne',
        'Christy Ucheibe',
        'Debora Abiodun',
        'Jennifer Echegini',
      ],
      attacker: [
        'Uchenna Kanu',
        'Gift Monday',
        'Ifeoma Onumonu',
        'Asisat Oshoala',
        'Desire Oparanozie',
        'Francisca Ordega',
        'Esther Okoronkwo',
      ],
      coach: 'Randy Waldrum',
    },
  },
  {
    name: 'Norway',
    capital: 'Oslo',
    code: 'NOR',
    region: 'Europe',
    population: 5379475,
    flag: 'https://flagcdn.com/no.svg',
    players: {
      goalkeeper: ['Cecilie Fiskerstrand', 'Aurora Mikalsen', 'Guro Pettersen'],
      defender: [
        'Maren Mjelde',
        'Anja Sonstevold',
        'Tuva Hansen',
        'Guro Bergsvand',
        'Mathilde Harviken',
        'Marit Lund',
        'Sara Horte',
        '.',
      ],
      midfield: [
        'Guro Reiten',
        'Frida Maanum',
        'Vilde Rise',
        'Ingrid Engen',
        'Amalie Eikeland',
        'Julie Blakstad',
        'Thea Bjelde',
      ],
      attacker: [
        'Carolina Graham Hansen',
        'Emilie Haavi',
        'Ada Hegerberg',
        'Karina Saevik',
        'Sophie Haug',
        'Anna Josendal',
      ],
      coach: 'Hege Riise',
    },
  },
  {
    name: 'Panama',
    capital: 'Panama City',
    code: 'PAN',
    region: 'Americas',
    population: 4314768,
    flag: 'https://flagcdn.com/pa.svg',
    players: {
      goalkeeper: ['Sasha Fábrega', 'Yenith Bailey', 'Farissa Córdoba'],
      defender: [
        'Hilary Jaén',
        'Wendy Natis',
        'Katherine Castillo',
        'Yomira Pinzón',
        'Rosario Vargas',
        'Rebeca Espinosa',
        'Nicole de Obaldía',
        'CArina Baltrip-Reyes',
      ],
      midfield: [
        'Deysiré Salazar',
        'Emily Cedeño',
        'Schiandra González',
        'Marta Cox',
        'Natalia Mills',
        'Carmen Montenegro',
        'Laurie Batista',
        'Erika Hernández',
        'Aldrith Quintero',
      ],
      attacker: ['Karla Riley', 'Riley Tanner', 'Lineth Cedeño'],
      coach: 'Ignacio Quintana',
    },
  },
  {
    name: 'Philippines',
    capital: 'Manila',
    code: 'PHL',
    region: 'Asia',
    population: 109581085,
    flag: 'https://flagcdn.com/ph.svg',
    players: {
      goalkeeper: ['Kiara Fontanilla', 'Kaiya Jota', 'Olivia McDaniel'],
      defender: [
        'Maya Alcantara',
        'Alicia Barker',
        'Angela Beard',
        'Reina Bonta',
        'Malea Cesar',
        'Jessika Cowart',
        'Hali Long',
        'Sofia Harrison',
        'Dominique Randle',
      ],
      midfield: [
        'Tahnai Annis',
        'Anicka Castañeda',
        'Sara Eggesvik',
        'Quinley Quezada',
        'Jaclyn Sawicki',
      ],
      attacker: [
        'Sarina Bolden',
        'Isabella Flanigan',
        'Carleigh Frilles',
        'Katrina Guillou',
        'Chadler McDaniel',
        'Meryll Serrano',
      ],
      coach: 'Alen Stajcic',
    },
  },
  {
    name: 'Portugal',
    capital: 'Lisbon',
    code: 'PRT',
    region: 'Europe',
    population: 10305564,
    flag: 'https://flagcdn.com/pt.svg',
    players: {
      goalkeeper: ['Rute Costa', 'Inês Pereira', 'Patrícia Morais'],
      defender: [
        'Ana Seiça',
        'Carole Costa',
        'Catarina Amado',
        'Diana Gomes',
        'Joana Marchão',
        'Lúcia Alves',
        'Sílvia Rebelo',
      ],
      midfield: [
        'Ana Rute',
        'Andreia Norton',
        'Andreia Jacinto',
        'Dolores Silva',
        'Fátima Pinto',
        "Francisca 'Kika' Nazareth",
        'Tatiana Pinto',
      ],
      attacker: [
        'Ana Borges',
        'Ana Capeta',
        'Carolina Mendes',
        'Diana Silva',
        'Jéssica Silva',
        'Telma Encarnação',
      ],
      coach: 'Francisco Neto',
    },
  },
  {
    name: 'Ireland',
    capital: 'Dublin',
    code: 'IRL',
    region: 'Europe',
    population: 4994724,
    flag: 'https://flagcdn.com/ie.svg',
    players: {
      goalkeeper: ['Courtney Brosnan', 'Grace Moloney', 'Megan Walsh'],
      defender: [
        "Aine O'Gorman",
        'Niamh Fahey',
        'Louise Quinn',
        'Diane Caldwell',
        'Heather Payne',
        "Claire O'Riordan",
        'Chloe Mustaki',
        'Isibeal Atkinson',
      ],
      midfield: [
        "Denise O'Sullivan",
        'Katie McCabe',
        'Ruesha Littlejohn',
        'Megan Connolly',
        'Ciara Grant',
        'Lucy Quinn',
        'Lily Agg',
        'Sinead Farrelly',
      ],
      attacker: [
        'Amber Barrett',
        'Kyra Carusa',
        'Abbie Larkin',
        'Marissa Sheva',
      ],
      coach: 'Vera Pauw',
    },
  },
  {
    name: 'South Africa',
    capital: 'Pretoria',
    code: 'ZAF',
    region: 'Africa',
    population: 59308690,
    flag: 'https://flagcdn.com/za.svg',
    players: {
      goalkeeper: ['Andile Dlamini', 'Kaylin Swart', 'Kebotseng Moletsane'],
      defender: [
        'Karabo Dhlamini',
        'Fikilie Magama',
        'Lebohang Ramalepe',
        'Tiisetso Makhubela',
        'Noko Matlou',
        'Bambanani Mbane',
        'Bongeka Gamede',
      ],
      midfield: [
        'Kholosa Biyana',
        'Refiloe Jane',
        'Sibulele Holweni',
        'Linda Motlhalo',
        'Nomvula Kgoale',
        'Robyn Moodaly',
      ],
      attacker: [
        'Gabriela Salgado',
        'Jermaine Seoposenwe',
        'Noxolo Cesane',
        'Melinda Kgadiete',
        'Wendy Shongwe',
        'Hildah Magaia',
        'Thembi Kgantlana',
      ],
      coach: 'Desiree Ellis',
    },
  },
  {
    name: 'Spain',
    capital: 'Madrid',
    code: 'ESP',
    region: 'Europe',
    population: 47351567,
    flag: 'https://flagcdn.com/es.svg',
    players: {
      goalkeeper: ['Misa Rodriguez', 'Enith Salón', 'Cata Coll'],
      defender: [
        'Ivana Andrés',
        'Ona Batlle',
        'Olga Carmona',
        'Laia Codina',
        'Rocío Gálvez',
        'Oihane Hernández',
        'Irene Paredes',
      ],
      midfield: [
        'Tere Abelleira',
        'Aitana Bonmatí',
        'Irene Guerrero',
        'Jenni Hermoso',
        'María Pérez',
        'Alexia Putellas',
        'Claudia Zornoza',
      ],
      attacker: [
        'Mariona Caldentey',
        'Athenea del Castillo',
        'Esther González',
        'Eva Navarro',
        'Salma Paralluelo',
        'Alba Redondo',
      ],
      coach: 'Jorge Vilda',
    },
  },
  {
    name: 'Sweden',
    capital: 'Stockholm',
    code: 'SWE',
    region: 'Europe',
    population: 10353442,
    flag: 'https://flagcdn.com/se.svg',
    players: {
      goalkeeper: ['Jennifer Falk', 'Zecira Musovic', 'Tove Enblom'],
      defender: [
        'Linda Sembrant',
        'Magdalena Eriksson',
        'Jonna Andersson',
        'Amanda Ilestedt',
        'Nathalie Björn',
        'Hanna Lundkvist',
        'Anna Sandberg',
      ],
      midfield: [
        'Caroline Seger',
        'Kosovare Asllani',
        'Olivia Schough',
        'Elin Rubensson',
        'Filippa Angeldahl',
        'Hanna Bennison',
        'Johanna Rytting Kaneryd',
      ],
      attacker: [
        'Sofia Jakobsson',
        'Stina Blackstenius',
        'Fridolina Rolfö',
        'Lina Hurtig',
        'Madelen Janogy',
        'Rebecka Blomqvist',
      ],
      coach: 'Peter Gerhardsson',
    },
  },
  {
    name: 'Switzerland',
    capital: 'Bern',
    code: 'CHE',
    region: 'Europe',
    population: 8636896,
    flag: 'https://flagcdn.com/ch.svg',
    players: {
      goalkeeper: ['Gaëlle Thalmann', 'Seraina Friedli', 'Livia Peng'],
      defender: [
        'Noelle Maritz',
        'Eseosa Algbogun',
        'Viola Calligaris',
        'Luana Bühler',
        'Julia Stierli',
        'Lara Marti',
        'Nadine Riesen',
        'Laura Felber',
      ],
      midfield: [
        'Lia Wälti',
        'Géraldine Reuteler',
        'Coumba Sow',
        'Sandrine Mauron',
        'Seraina Plubel',
        'Marion Rey',
        'Iman Beney',
      ],
      attacker: [
        'Ana Crnogorcevic',
        'Ramona Bachmann',
        'Fabienne Humm',
        'Alisha Lehmann',
        'Meriame Terchoun',
      ],
      coach: 'Inka Grings',
    },
  },
  {
    name: 'United States',
    capital: 'Washington, D.C.',
    code: 'USA',
    region: 'Americas',
    population: 329484123,
    flag: 'https://flagcdn.com/us.svg',
    players: {
      goalkeeper: ['Alyssa Naeher', 'Casey Murphy', 'Aubrey Kingsbury'],
      defender: [
        'Sofia Herta',
        'Naomi Girma',
        "Kelley O'Hara",
        'Alana Cook',
        'Emily Sonnett',
        'Crystal Dunn',
        'Emily Fox',
      ],
      midfield: [
        'Ashley Sanchez',
        'Julie Ertz',
        'Savannah DeMelo',
        'Lindsey Horan',
        'Rose Lavelle',
        'Andi Sullivan',
        'Kristie Mewis',
      ],
      attacker: [
        'Lynn Williams',
        'Alyssa Thompson',
        'Sophia Smith',
        'Alex Morgan',
        'Megan Rapinoe',
        'Trinity Rodman',
      ],
      coach: 'Vlatko Andonovski',
    },
  },
  {
    name: 'Vietnam',
    capital: 'Hanoi',
    code: 'VNM',
    region: 'Asia',
    population: 97338583,
    flag: 'https://flagcdn.com/vn.svg',
    players: {
      goalkeeper: ['Tran Thi Kim Thanh', 'Khong Thi Hang', 'Dao Thi Kieu Oanh'],
      defender: [
        'Chuong Thi Kieu',
        'Tran Thi Thu Thao',
        'Hoang Thi Loan',
        'Tran Thi Thu',
        'Luong Thi Thu Thuong',
        'Nguyen Thi My Anh',
        'Le Thi Diem My',
        'Tran Thi Hai Linh',
        'Tran Thi Thuy Nga',
      ],
      midfield: [
        'Nguyen Thi Tuyet Dung',
        'Duong Thi Van',
        'Tran Thi Thuy Trang',
        'Nguyen Thi Bich Thuy',
        'Thai Thi Thao',
        'Nguyen Thi Thanh Nhã',
        'Ngan Thi Van Su',
      ],
      attacker: [
        'Huynh Nhu',
        'Pham Hai Yen',
        'Nguyen Thi Thuy Hang',
        'Vu Thi Hoa',
      ],
      coach: 'Mai Duc Chung',
    },
  },
  {
    name: 'Zambia',
    capital: 'Lusaka',
    code: 'ZMB',
    region: 'Africa',
    population: 18383956,
    flag: 'https://flagcdn.com/zm.svg',
    players: {
      goalkeeper: ['Catherine Musonda', 'Eunice Sakala'],
      defender: [
        'Margaret Belemu',
        'Martha Tembo',
        'Lushomo Mweemba',
        'Agness Musase',
        'Esther Banda',
        'Judith Soko',
        'Mary Mulenga',
        'Vast Phiri',
      ],
      midfield: [
        'Ireen Lungu',
        'Hellen Chanda',
        'Evarine Katongo',
        'Mary Wilombe',
        'Susan Banda',
        'Avell Chitundu',
      ],
      attacker: [
        'Xiomara Mapepa',
        'Ochumba Lubandji',
        'Racheal Nachula',
        'Grace Chanda',
        'Racheal Kundananji',
        'Barbra Banda',
      ],
      coach: 'Bruce Mwape',
    },
  },
];

export { teams };
